version: "2"
plugins:
  duplication:
    enabled: true
    exclude_patterns:
      - 'app/**/*.tsx'
  rubocop:
    enabled: true
    channel: "beta"
checks:
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-lines:
    enabled: true
    config:
      threshold: 150
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/*.d.ts"
- babel.config.js