# Default values for rails-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  image:
    repository: kevin9tq/template
    tag: v1.0.7
  replicaCount: 1
  environment: production
  pumaConcurrency: "2"
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 1Gi
  # env:
  #   - name: GOOGLE_CLIENT_ID
  #     value: value

imagePullSecrets:
  - name: regcred

redis:
  enabled: false
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
      size: 1Gi
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 256Mi

sidekiq:
  enabled: false
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 512Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  ssl: "letsencrypt"
  className: nginx
  host: template.9tq.ovh
  annotations:
    # kubernetes.io/tls-acme: "true"

autoscaling:
  enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80

mariadb:
  enabled: true
  auth:
    username: "templatep"
    database: "template_production"
    existingSecret: "mariadbcred"
  primary:
    resources:
      limits:
        memory: 1Gi